--- 
apiVersion: mxnet.mlkube.io/v1beta1
kind: MxJob
metadata: 
  name: mxnet-cluster-mnist-gpu
spec: 
  jobMode: dist
  replicaSpecs: 
    - 
      PsRootPort: 9090
      mxReplicaType: SCHEDULER
      replicas: 1
      template: 
        spec: 
          containers: 
            - 
              args: 
                - /workdir/script/mxnetClusterMnistGPU.py
              command: 
                - python
              image: "mxnet-gpu-cuda9-dist:0.12.0"
              imagePullPolicy: Never
              name: mxnet
              volumeMounts: 
                - 
                  mountPath: /workdir
                  name: workdir
                - 
                  mountPath: /usr/local/nvidia
                  name: nvidia-libraries
          nodeSelector: 
            kubernetes.io/hostname: test-86-081
          restartPolicy: OnFailure
          volumes: 
            - 
              hostPath: 
                path: /root/junzhang22/mxnet_training
              name: workdir
            - 
              hostPath: 
                path: /var/lib/nvidia-docker/volumes/nvidia_driver/387.26
              name: nvidia-libraries
    - 
      mxReplicaType: SERVER
      replicas: 1
      template: 
        spec: 
          containers: 
            - 
              args: 
                - /workdir/script/mxnetClusterMnistGPU.py
              command: 
                - python
              image: "mxnet-gpu-cuda9-dist:0.12.0"
              imagePullPolicy: Never
              name: mxnet
              volumeMounts: 
                - 
                  mountPath: /workdir
                  name: workdir
                - 
                  mountPath: /usr/local/nvidia
                  name: nvidia-libraries
          nodeSelector: 
            kubernetes.io/hostname: test-86-081
          restartPolicy: OnFailure
          volumes: 
            - 
              hostPath: 
                path: /root/junzhang22/mxnet_training
              name: workdir
            - 
              hostPath: 
                path: /var/lib/nvidia-docker/volumes/nvidia_driver/387.26
              name: nvidia-libraries
    - 
      mxReplicaType: WORKER
      replicas: 1
      template: 
        spec: 
          containers: 
            - 
              args: 
                - /workdir/script/mxnetClusterMnistGPU.py
              command: 
                - python
              image: "mxnet-gpu-cuda9-dist:0.12.0"
              imagePullPolicy: Never
              name: mxnet
              resources: 
                limits: 
                  alpha.kubernetes.io/nvidia-gpu: 1
              volumeMounts: 
                - 
                  mountPath: /workdir
                  name: workdir
          nodeSelector: 
            kubernetes.io/hostname: test-86-081
          restartPolicy: OnFailure
          volumes: 
            - 
              hostPath: 
                path: /root/junzhang22/mxnet_training
              name: workdir
